"""Add farmbot config resource

Revision ID: 226dde11a138
Revises: 5c1825290fc4
Create Date: 2021-01-07 17:44:09.495876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226dde11a138'
down_revision = '5c1825290fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmbot_config',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmbot_config')
    # ### end Alembic commands ###
