"""add comment to sequence

Revision ID: 6cdb3b5351e1
Revises: 94a6ef17d511
Create Date: 2021-08-20 11:22:18.485246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cdb3b5351e1'
down_revision = '94a6ef17d511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence', sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence', 'comments')
    # ### end Alembic commands ###
