"""add actions to sequence resource

Revision ID: 7ed25edd57a2
Revises: 515dc4055d63
Create Date: 2021-02-01 15:25:33.447804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ed25edd57a2'
down_revision = '515dc4055d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence', 'actions')
    # ### end Alembic commands ###
