"""empty message

Revision ID: 94a6ef17d511
Revises: e9ab5e78a5ab
Create Date: 2021-03-26 12:12:19.281889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94a6ef17d511'
down_revision = 'e9ab5e78a5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence', sa.Column('fb_seq_id', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence', 'fb_seq_id')
    # ### end Alembic commands ###
