"""Add user group

Revision ID: b1b8b93e81c5
Revises: 6cdb3b5351e1
Create Date: 2021-08-31 12:24:49.833285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1b8b93e81c5'
down_revision = '6cdb3b5351e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('challenge', sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('challenge_group_fkey', 'challenge', 'user_group', ['group_id'], ['id'])
    op.add_column('user', sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('user_group_fkey', 'user', 'user_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.drop_constraint('challenge_group_fkey', 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'group_id')
    op.drop_table('user_group')
    # ### end Alembic commands ###
