"""Initial migration.

Revision ID: c63d06374f79
Revises: 
Create Date: 2020-12-14 17:10:33.991840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c63d06374f79'
down_revision = None
branch_labels = None
depends_on = None

userroles = sa.Enum('ADMIN', 'USER', name='userroles')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pseudo', sa.String(length=64), nullable=False, unique=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False, unique=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userroles'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    userroles.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
