"""add farmbot pin config

Revision ID: e9ab5e78a5ab
Revises: 7ed25edd57a2
Create Date: 2021-03-12 15:01:57.870189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9ab5e78a5ab'
down_revision = '7ed25edd57a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('material_type', sa.Enum('PERIPHERAL', 'SENSOR', name='materialtypes'), nullable=False),
    sa.Column('material_id', sa.SMALLINT(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id'),
    sa.UniqueConstraint('action')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pin')
    # ### end Alembic commands ###
